version: '3.8'

services:
  frontend:
    image: ghcr.io/${GITHUB_REPOSITORY}/kleos-frontend:latest
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always

  backend:
    image: ghcr.io/${GITHUB_REPOSITORY}/kleos-backend:latest
    env_file:
      - .env
    expose:
      - "8000"
    restart: always
